### ISSUE TITLE
How to deal with different algorithm (3d vs 2d) ?

### ISSUE THREAD

**Issue by hydroflame** [hydroflame/juntos#3]

**Comment by hydroflame** [comment]
do we use build tags ?
do we use a sort of preprocessor ?

**Comment by EtienneBruines** [comment]
* What's the overhead in defining 2d stuff in a 3d environment? 
(i.e. a static z-value, default rotation value, etc.) 
* How do we feel about doing this like I've seen in OpenGL (note that I haven't seen much) - methods with parameters X, Y, and methods with parameters X, Y, Z.

**Comment by hydroflame** [comment]
The rendering part is the super easy part and performance loss should be minimal.

The complex parts are all the algorithms, like occlusion culling, rigid body integration, collision detection etc

**Comment by hydroflame** [comment]
example (comments removed for brievety):

	type Ray struct {
		origin glm.Vec3
		direction glm.Vec3
		len float32
	}

either we have build tags

	// +build 3d

	type Ray struct {
		origin glm.Vec3
		direction glm.Vec3
		len float32
	}

but i feel build tag means we're just gonna have 2 files for everything ever

or some kind of preprocessor

	type Ray struct {
		origin glm.Vec{{.Dimention}}
		direction glm.Vec{{.Dimention}}
		len float32
	}

	func NewRayFromTo(from, to glm.Vec{{.Dimention}}) Ray {
		dir := to.Sub(&from)
		normal := dir.Normalized()
		if math.IsNaN(normal[0]) || math.IsNaN(normal[1]){{if eq .Dimention 3}} || math.IsNaN(normal[2]) {{end}} {
			normal = glm.Vec{{.Dimention}}{0, 1{{if eq .Dimention 3}}, 0{{end}}}
		}
		return Ray{
			origin:    from,
			direction: normal,
			len:       dir.Len(),
		}
	}

which is super ugly and hard to code :\

**Comment by EtienneBruines** [comment]
I'm not sure; what does this `Ray` do in 3d and 2d?

**Comment by hydroflame** [comment]
its a ... `Ray` so you use this to cast like a giant rod in the world and see with that this collides, you can use this to know if the mouse click is coliding with an object

**Comment by EtienneBruines** [comment]
I get [your point](https://github.com/hydroflame/juntos/issues/3#issuecomment-163241347).

**Comment by EtienneBruines** [comment]
What's the harm in having a Ray in 2d? (or basically: anything that's very useful in 3d, but not so much in 2d)

I mean, people would just not use it; even though the code is there. The algorithm for 2d and 3d doesn't have to be different. 2d might be more efficient, but that's about it for the changes in algorithms. (as you can view 2d as a special form of 3d).

**Comment by hydroflame** [comment]
i gave that example for the simple more then the usefullness of rays (although they really are usefull even in 2d)

However some algorithms would have quite a different API in 2d vs 3d, like occlusion culling

**Comment by hydroflame** [comment]
While writing github.com/luxengine/glm/geo I realised that most 2d vs 3d algorithm are totally different, so we just have to rewrite them for both
